version: "3.9"

services:
  app:
    build:
      context: .
    container_name: import_users_app
    image: import_users_app:0.1.0
    env_file:
      - .env
    volumes:
      - ./import_users:/home/user/app
